apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: redmine
  name: redmine
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redmine
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: redmine
    spec:
      containers:
        - image: redmine
          name: redmine
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
